# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masking_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='masking_config.proto',
  package='sound',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14masking_config.proto\x12\x05sound\"\xb5\x01\n\x12\x41uditoryBandConfig\x12<\n\x0e\x61uditory_bands\x18\x01 \x03(\x0b\x32$.sound.AuditoryBandConfig.SingleBand\x12\x14\n\x0c\x66ilter_order\x18\x02 \x01(\x03\x1aK\n\nSingleBand\x12\x12\n\nstart_freq\x18\x01 \x01(\x03\x12\x11\n\tstop_freq\x18\x02 \x01(\x03\x12\x16\n\x0e\x63ritical_ratio\x18\x03 \x01(\x03\"|\n\rMaskingConfig\x12\x37\n\x14\x61uditory_band_config\x18\x01 \x01(\x0b\x32\x19.sound.AuditoryBandConfig\x12\x1a\n\x12window_duration_ms\x18\x02 \x01(\x03\x12\x16\n\x0ewindow_step_ms\x18\x03 \x01(\x03\x62\x06proto3')
)




_AUDITORYBANDCONFIG_SINGLEBAND = _descriptor.Descriptor(
  name='SingleBand',
  full_name='sound.AuditoryBandConfig.SingleBand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_freq', full_name='sound.AuditoryBandConfig.SingleBand.start_freq', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_freq', full_name='sound.AuditoryBandConfig.SingleBand.stop_freq', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='critical_ratio', full_name='sound.AuditoryBandConfig.SingleBand.critical_ratio', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=213,
)

_AUDITORYBANDCONFIG = _descriptor.Descriptor(
  name='AuditoryBandConfig',
  full_name='sound.AuditoryBandConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auditory_bands', full_name='sound.AuditoryBandConfig.auditory_bands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter_order', full_name='sound.AuditoryBandConfig.filter_order', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUDITORYBANDCONFIG_SINGLEBAND, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=213,
)


_MASKINGCONFIG = _descriptor.Descriptor(
  name='MaskingConfig',
  full_name='sound.MaskingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auditory_band_config', full_name='sound.MaskingConfig.auditory_band_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window_duration_ms', full_name='sound.MaskingConfig.window_duration_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window_step_ms', full_name='sound.MaskingConfig.window_step_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=339,
)

_AUDITORYBANDCONFIG_SINGLEBAND.containing_type = _AUDITORYBANDCONFIG
_AUDITORYBANDCONFIG.fields_by_name['auditory_bands'].message_type = _AUDITORYBANDCONFIG_SINGLEBAND
_MASKINGCONFIG.fields_by_name['auditory_band_config'].message_type = _AUDITORYBANDCONFIG
DESCRIPTOR.message_types_by_name['AuditoryBandConfig'] = _AUDITORYBANDCONFIG
DESCRIPTOR.message_types_by_name['MaskingConfig'] = _MASKINGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuditoryBandConfig = _reflection.GeneratedProtocolMessageType('AuditoryBandConfig', (_message.Message,), dict(

  SingleBand = _reflection.GeneratedProtocolMessageType('SingleBand', (_message.Message,), dict(
    DESCRIPTOR = _AUDITORYBANDCONFIG_SINGLEBAND,
    __module__ = 'masking_config_pb2'
    # @@protoc_insertion_point(class_scope:sound.AuditoryBandConfig.SingleBand)
    ))
  ,
  DESCRIPTOR = _AUDITORYBANDCONFIG,
  __module__ = 'masking_config_pb2'
  # @@protoc_insertion_point(class_scope:sound.AuditoryBandConfig)
  ))
_sym_db.RegisterMessage(AuditoryBandConfig)
_sym_db.RegisterMessage(AuditoryBandConfig.SingleBand)

MaskingConfig = _reflection.GeneratedProtocolMessageType('MaskingConfig', (_message.Message,), dict(
  DESCRIPTOR = _MASKINGCONFIG,
  __module__ = 'masking_config_pb2'
  # @@protoc_insertion_point(class_scope:sound.MaskingConfig)
  ))
_sym_db.RegisterMessage(MaskingConfig)


# @@protoc_insertion_point(module_scope)
