# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sound.proto',
  package='sound',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bsound.proto\x12\x05sound\"Y\n\x11SpectrogramConfig\x12\x13\n\x0bwindow_type\x18\x01 \x01(\t\x12\x0f\n\x07nperseg\x18\x02 \x01(\x03\x12\x10\n\x08noverlap\x18\x03 \x01(\x03\x12\x0c\n\x04nfft\x18\x04 \x01(\x03\x62\x06proto3')
)




_SPECTROGRAMCONFIG = _descriptor.Descriptor(
  name='SpectrogramConfig',
  full_name='sound.SpectrogramConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window_type', full_name='sound.SpectrogramConfig.window_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nperseg', full_name='sound.SpectrogramConfig.nperseg', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='noverlap', full_name='sound.SpectrogramConfig.noverlap', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nfft', full_name='sound.SpectrogramConfig.nfft', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['SpectrogramConfig'] = _SPECTROGRAMCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpectrogramConfig = _reflection.GeneratedProtocolMessageType('SpectrogramConfig', (_message.Message,), dict(
  DESCRIPTOR = _SPECTROGRAMCONFIG,
  __module__ = 'sound_pb2'
  # @@protoc_insertion_point(class_scope:sound.SpectrogramConfig)
  ))
_sym_db.RegisterMessage(SpectrogramConfig)


# @@protoc_insertion_point(module_scope)
